// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jWKqvDKQX9h2I_KT2p7IddKzV0rN41s',
    appId: '1:171655642759:web:7cf15be0061495a0bb0222',
    messagingSenderId: '171655642759',
    projectId: 'mobileapp-auth-b837d',
    authDomain: 'mobileapp-auth-b837d.firebaseapp.com',
    storageBucket: 'mobileapp-auth-b837d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5bm5pvPsOzm_hSOlAfG6sW4XPlwjwHY',
    appId: '1:171655642759:android:7459f9937cd4cbd9bb0222',
    messagingSenderId: '171655642759',
    projectId: 'mobileapp-auth-b837d',
    storageBucket: 'mobileapp-auth-b837d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpuNaL18vVo2Qfk8y-aFRjQWHOf_YTm-I',
    appId: '1:171655642759:ios:343488a383aeb90dbb0222',
    messagingSenderId: '171655642759',
    projectId: 'mobileapp-auth-b837d',
    storageBucket: 'mobileapp-auth-b837d.appspot.com',
    androidClientId: '171655642759-r56phtp74l1gtahejme0h9ms4q4luobv.apps.googleusercontent.com',
    iosClientId: '171655642759-ge3mbd0vm2rigm9e5o184nuisbpe7ro4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpuNaL18vVo2Qfk8y-aFRjQWHOf_YTm-I',
    appId: '1:171655642759:ios:343488a383aeb90dbb0222',
    messagingSenderId: '171655642759',
    projectId: 'mobileapp-auth-b837d',
    storageBucket: 'mobileapp-auth-b837d.appspot.com',
    androidClientId: '171655642759-r56phtp74l1gtahejme0h9ms4q4luobv.apps.googleusercontent.com',
    iosClientId: '171655642759-ge3mbd0vm2rigm9e5o184nuisbpe7ro4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreapp',
  );
}
